// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: modelproto/v2/service.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IntakeResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IntakeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntakeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IntakeResponseMultiError,
// or nil if none found.
func (m *IntakeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IntakeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetErrors() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntakeResponseValidationError{
						field:  fmt.Sprintf("Errors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntakeResponseValidationError{
						field:  fmt.Sprintf("Errors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntakeResponseValidationError{
					field:  fmt.Sprintf("Errors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return IntakeResponseMultiError(errors)
	}

	return nil
}

// IntakeResponseMultiError is an error wrapping multiple validation errors
// returned by IntakeResponse.ValidateAll() if the designated constraints
// aren't met.
type IntakeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntakeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntakeResponseMultiError) AllErrors() []error { return m }

// IntakeResponseValidationError is the validation error returned by
// IntakeResponse.Validate if the designated constraints aren't met.
type IntakeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntakeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntakeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntakeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntakeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntakeResponseValidationError) ErrorName() string { return "IntakeResponseValidationError" }

// Error satisfies the builtin error interface
func (e IntakeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntakeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntakeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntakeResponseValidationError{}

// Validate checks the field values on IntakeError with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IntakeError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntakeError with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IntakeErrorMultiError, or
// nil if none found.
func (m *IntakeError) ValidateAll() error {
	return m.validate(true)
}

func (m *IntakeError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return IntakeErrorMultiError(errors)
	}

	return nil
}

// IntakeErrorMultiError is an error wrapping multiple validation errors
// returned by IntakeError.ValidateAll() if the designated constraints aren't met.
type IntakeErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntakeErrorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntakeErrorMultiError) AllErrors() []error { return m }

// IntakeErrorValidationError is the validation error returned by
// IntakeError.Validate if the designated constraints aren't met.
type IntakeErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntakeErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntakeErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntakeErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntakeErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntakeErrorValidationError) ErrorName() string { return "IntakeErrorValidationError" }

// Error satisfies the builtin error interface
func (e IntakeErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntakeError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntakeErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntakeErrorValidationError{}
