// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: modelproto/v2/service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*IntakeError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *IntakeResponse) Reset() {
	*x = IntakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelproto_v2_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntakeResponse) ProtoMessage() {}

func (x *IntakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modelproto_v2_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntakeResponse.ProtoReflect.Descriptor instead.
func (*IntakeResponse) Descriptor() ([]byte, []int) {
	return file_modelproto_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *IntakeResponse) GetErrors() []*IntakeError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type IntakeError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IntakeError) Reset() {
	*x = IntakeError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelproto_v2_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntakeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntakeError) ProtoMessage() {}

func (x *IntakeError) ProtoReflect() protoreflect.Message {
	mi := &file_modelproto_v2_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntakeError.ProtoReflect.Descriptor instead.
func (*IntakeError) Descriptor() ([]byte, []int) {
	return file_modelproto_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *IntakeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_modelproto_v2_service_proto protoreflect.FileDescriptor

var file_modelproto_v2_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x32, 0x1a, 0x19, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0e,
	0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x61, 0x6b,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x42, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x31, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x09, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x76,
	0x32, 0x2e, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x48, 0x01, 0x5a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modelproto_v2_service_proto_rawDescOnce sync.Once
	file_modelproto_v2_service_proto_rawDescData = file_modelproto_v2_service_proto_rawDesc
)

func file_modelproto_v2_service_proto_rawDescGZIP() []byte {
	file_modelproto_v2_service_proto_rawDescOnce.Do(func() {
		file_modelproto_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_modelproto_v2_service_proto_rawDescData)
	})
	return file_modelproto_v2_service_proto_rawDescData
}

var file_modelproto_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modelproto_v2_service_proto_goTypes = []interface{}{
	(*IntakeResponse)(nil), // 0: v2.IntakeResponse
	(*IntakeError)(nil),    // 1: v2.IntakeError
	(*Event)(nil),          // 2: v2.Event
}
var file_modelproto_v2_service_proto_depIdxs = []int32{
	1, // 0: v2.IntakeResponse.errors:type_name -> v2.IntakeError
	2, // 1: v2.IntakeService.IntakeEvents:input_type -> v2.Event
	0, // 2: v2.IntakeService.IntakeEvents:output_type -> v2.IntakeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modelproto_v2_service_proto_init() }
func file_modelproto_v2_service_proto_init() {
	if File_modelproto_v2_service_proto != nil {
		return
	}
	file_modelproto_v2_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_modelproto_v2_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelproto_v2_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntakeError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modelproto_v2_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modelproto_v2_service_proto_goTypes,
		DependencyIndexes: file_modelproto_v2_service_proto_depIdxs,
		MessageInfos:      file_modelproto_v2_service_proto_msgTypes,
	}.Build()
	File_modelproto_v2_service_proto = out.File
	file_modelproto_v2_service_proto_rawDesc = nil
	file_modelproto_v2_service_proto_goTypes = nil
	file_modelproto_v2_service_proto_depIdxs = nil
}
