// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntakeServiceClient is the client API for IntakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntakeServiceClient interface {
	IntakeEvents(ctx context.Context, opts ...grpc.CallOption) (IntakeService_IntakeEventsClient, error)
}

type intakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntakeServiceClient(cc grpc.ClientConnInterface) IntakeServiceClient {
	return &intakeServiceClient{cc}
}

func (c *intakeServiceClient) IntakeEvents(ctx context.Context, opts ...grpc.CallOption) (IntakeService_IntakeEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IntakeService_ServiceDesc.Streams[0], "/v2.IntakeService/IntakeEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &intakeServiceIntakeEventsClient{stream}
	return x, nil
}

type IntakeService_IntakeEventsClient interface {
	Send(*Event) error
	Recv() (*IntakeResponse, error)
	grpc.ClientStream
}

type intakeServiceIntakeEventsClient struct {
	grpc.ClientStream
}

func (x *intakeServiceIntakeEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intakeServiceIntakeEventsClient) Recv() (*IntakeResponse, error) {
	m := new(IntakeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntakeServiceServer is the server API for IntakeService service.
// All implementations must embed UnimplementedIntakeServiceServer
// for forward compatibility
type IntakeServiceServer interface {
	IntakeEvents(IntakeService_IntakeEventsServer) error
	mustEmbedUnimplementedIntakeServiceServer()
}

// UnimplementedIntakeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntakeServiceServer struct {
}

func (UnimplementedIntakeServiceServer) IntakeEvents(IntakeService_IntakeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method IntakeEvents not implemented")
}
func (UnimplementedIntakeServiceServer) mustEmbedUnimplementedIntakeServiceServer() {}

// UnsafeIntakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntakeServiceServer will
// result in compilation errors.
type UnsafeIntakeServiceServer interface {
	mustEmbedUnimplementedIntakeServiceServer()
}

func RegisterIntakeServiceServer(s grpc.ServiceRegistrar, srv IntakeServiceServer) {
	s.RegisterService(&IntakeService_ServiceDesc, srv)
}

func _IntakeService_IntakeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntakeServiceServer).IntakeEvents(&intakeServiceIntakeEventsServer{stream})
}

type IntakeService_IntakeEventsServer interface {
	Send(*IntakeResponse) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type intakeServiceIntakeEventsServer struct {
	grpc.ServerStream
}

func (x *intakeServiceIntakeEventsServer) Send(m *IntakeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intakeServiceIntakeEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntakeService_ServiceDesc is the grpc.ServiceDesc for IntakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2.IntakeService",
	HandlerType: (*IntakeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IntakeEvents",
			Handler:       _IntakeService_IntakeEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "modelproto/v2/service.proto",
}
